# Generated by Django 5.1 on 2024-08-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_task', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rate_limit',
            new_name='RateLimit',
        ),
    ]
