# Generated by Django 3.2.12 on 2024-08-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('f', 'FSC'), ('m', 'MATRIC'), ('g', 'Graduation')], max_length=1, null=True),
        ),
    ]
