# Generated by Django 5.1 on 2024-08-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("f", "FSC"), ("m", "MATRIC"), ("g", "Graduation")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("is_sportsman", models.BooleanField(default=False)),
                ("is_speaker", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Speaker",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("practice.student",),
        ),
        migrations.CreateModel(
            name="Sportsman",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("practice.student",),
        ),
    ]
